name: rod
channels:
  - conda-forge
dependencies:
  # Core runtime dependencies
  - coloredlogs
  - mashumaro
  - numpy
  - packaging
  - resolve-robotics-uri-py
  - scipy
  - trimesh
  - xmltodict

  # Development and testing
  - black
  - isort
  - pytest
  - pytest-icdiff

  # Optional dependencies
  - pptree
  - idyntree
  - robot_descriptions

  # Gazebo/SDF processing
  - libgz-tools2
  - libsdformat13

  # Python packaging
  - hatchling
  - hatch-vcs
