name: Code Style

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:

  black:

    name: black
    runs-on: ubuntu-latest

    steps:

      - name: "🔀 Checkout repository"
        uses: actions/checkout@v2

      - name: '🐍 Initialize Python'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "📝 Black Code Formatter"
        uses: psf/black@stable
        with:
          options: --check --diff --color

  isort:

    name: isort
    runs-on: ubuntu-latest

    steps:

      - name: "🔀 Checkout repository"
        uses: actions/checkout@v2

      - name: '🐍 Initialize Python'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Workaround for https://github.com/isort/isort-action/issues/70
      - run: pip install colorama

      - name: "📝 isort"
        uses: isort/isort-action@master
        with:
          configuration: --check --diff --color
